<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <Description>Provides in-process compilation and rendering of razor template source code, e.g. for email templating.</Description>
    <PackageTags>razor;email;template;templating;blazor</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Basic.Reference.Assemblies.Net100"/>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory"/>
    <PackageReference Include="Microsoft.Extensions.Logging"/>
    <PackageReference Include="Microsoft.Net.Compilers.Razor.Toolset" PrivateAssets="all" IncludeAssets="none" GeneratePathProperty="true"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="$(PkgMicrosoft_Net_Compilers_Razor_Toolset)\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.dll"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always"/>
  </ItemGroup>

</Project>
