<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Basic.Reference.Assemblies.Net100" Version="1.8.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0"/>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8" />
    <PackageReference Include="Microsoft.Net.Compilers.Razor.Toolset" PrivateAssets="all" IncludeAssets="none" GeneratePathProperty="true" Version="9.0.0-preview.25264.2"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="$(PkgMicrosoft_Net_Compilers_Razor_Toolset)\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.dll"/>
  </ItemGroup>

</Project>
