name: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --property:Version=${{ github.event.release.tag_name }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet nuget publish --skip-duplicate --api-key=${{ secrets.NUGET_API_KEY }}
